# Generated by Django 4.2.27 on 2026-01-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('PRODUCTEUR', 'Producteur'), ('GESTIONNAIRE', 'Gestionnaire')], default='PRODUCTEUR', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.arrondissement')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commune')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commune'),
        ),
    ]
