# Generated by Django 4.2.27 on 2026-01-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producteur',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='role',
        ),
        migrations.AlterField(
            model_name='producteur',
            name='arrondissement',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='commune',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(default='Non renseigné', max_length=150),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom',
            field=models.CharField(default='Non renseigné', max_length=150),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
