# Generated by Django 4.2.27 on 2026-01-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=10)),
                ('quantite', models.FloatField()),
                ('seuil_alerte', models.FloatField(default=100)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockage.entrepot')),
            ],
        ),
    ]
