# Generated by Django 4.2.27 on 2026-01-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField(help_text='en hectares')),
                ('localisation', models.CharField(max_length=255)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producteur')),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite', models.FloatField(help_text='en tonnes')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.parcelle')),
            ],
        ),
    ]
